version: '3.8'

services:
  px4-simulation:
    build: .
    container_name: px4-gazebo-sim
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - GZ_SIM_SYSTEM_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/gz-sim-8/plugins
      - GZ_SIM_RESOURCE_PATH=/usr/share/gz/gz-sim8
    ports:
      - "14550:14550/udp"
      - "14570:14570/udp"  
      - "14580:14580/udp"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./logs:/home/px4/PX4-Autopilot/log
    network_mode: "host"
    stdin_open: true
    tty: true
    
  mavproxy:
    image: px4-dev:latest
    container_name: px4-mavproxy
    depends_on:
      - px4-simulation
    command: ["mavproxy.py", "--master=udp:127.0.0.1:14550", "--out=udpout:host.docker.internal:14551"]
    network_mode: "host"
